ur5_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0
  gains:
    shoulder_pan_joint: { p: 4000,  d: 200, i: 1, i_clamp: 1 }
    shoulder_lift_joint: { p: 10000,  d: 200, i: 1, i_clamp: 1 }
    elbow_joint: { p: 5000,  d: 50, i: 10, i_clamp: 1 }
    wrist_1_joint: { p: 200,  d: 20, i: 10, i_clamp: 1 }
    wrist_2_joint: { p: 100,  d: 10, i: 0.1, i_clamp: 1 }
    wrist_3_joint: { p: 10,  d: 1, i: 0.1, i_clamp: 1 }